project_id = "agususzieosizftucxxq"

[functions.apptweak-ranking]
verify_jwt = false

[functions.apptweak-top-charts]
verify_jwt = false

[functions.apptweak-ranking-history]
verify_jwt = false

[functions.apptweak-metrics]
verify_jwt = false

[functions.apptweak-metrics-history]
verify_jwt = false

[functions.sync-to-sheets]
verify_jwt = false

[functions.unity-to-bigquery]
verify_jwt = false

[functions.unity-preview]
verify_jwt = false

[functions.appsflyer-ssot]
verify_jwt = false

[functions.snapchat-to-bigquery]
verify_jwt = false

[functions.snapchat-preview]
verify_jwt = false

[functions.snapchat-clear-bigquery]
verify_jwt = false

[functions.snapchat-reconcile]
verify_jwt = false

[functions.apptweak-rank-to-sheets]
verify_jwt = false

[functions.meta-to-bigquery]
verify_jwt = false

[functions.meta-preview]
verify_jwt = false

[functions.google-ads-to-bigquery]
verify_jwt = false

[functions.google-ads-preview]
verify_jwt = false

[functions.asc-downloads]
verify_jwt = false

[functions.unity-history]
verify_jwt = false

[functions.snapchat-history]
verify_jwt = false

[functions.meta-history]
verify_jwt = false

[functions.manage-schedules]
verify_jwt = false

[functions.google-ads-history]
verify_jwt = false

[functions.tiktok-history]
verify_jwt = false
