project_id = "agususzieosizftucxxq"

[functions.apptweak-ranking]
verify_jwt = false

[functions.apptweak-top-charts]
verify_jwt = false

[functions.apptweak-ranking-history]
verify_jwt = false

[functions.apptweak-metrics]
verify_jwt = false

[functions.apptweak-metrics-history]
verify_jwt = false

[functions.sync-to-sheets]
verify_jwt = false
